CATEGORIES = {
    ".NET Development": ".NET Development",
    "3D Printing": "3D Printing",
    "Accounts": "Accounts",
    "Acting": "Acting",
    "Aerospace Engineering": "aerospace",
    "Agriculture and Food Engineering": "Agriculture and Food Engineering",
    "Analytics": "Analytics",
    "Android App Development": "android",
    "Angular.js Development": "Angular.js Development",
    "Animation": "Animation",
    "Architecture": "Architecture",
    "Artificial Intelligence (AI)": "Artificial Intelligence (AI)",
    "ASP.NET Development": "asp.net",
    "Automobile Engineering": "Automobile Engineering",
    "Backend Development": "Backend Development",
    "Big Data": "Big Data",
    "Bioinformatics": "Bioinformatics",
    "Biology": "Biology",
    "Biotechnology Engineering": "biotech",
    "Blogging": "Blogging",
    "Brand Management": "Brand Management",
    "CAD Design": "CAD Design",
    "Campus Ambassador": "Campus Ambassador",
    "Chartered Accountancy (CA)": "Chartered Accountancy (CA)",
    "Chemical Engineering": "chemical",
    "Chemistry": "Chemistry",
    "Civil Engineering": "civil",
    "Client Servicing": "Client Servicing",
    "Cloud Computing": "Cloud Computing",
    "Commerce": "Commerce",
    "Company Secretary (CS)": "Company Secretary (CS)",
    "Computer Science": "Computer Science",
    "Computer Vision": "Computer Vision",
    "Content Writing": "Content Writing",
    "Copywriting": "Copywriting",
    "Creative Design": "Creative Design",
    "Creative Writing": "Creative Writing",
    "Customer Service": "Customer Service",
    "Cyber Security": "Cyber Security",
    "Data Entry": "Data Entry",
    "Data Science": "Data Science",
    "Database Building": "Database Building",
    "Design": "Design",
    "Digital Marketing": "Digital Marketing",
    "Editorial": "Editorial",
    "Electrical Engineering": "electrical",
    "Electronics Engineering": "electronics",
    "Embedded Systems": "Embedded Systems",
    "Energy Science and Engineering": "Energy Science and Engineering",
    "Engineering": "Engineering",
    "Engineering Design": "Engineering Design",
    "Engineering Physics": "Engineering Physics",
    "Environmental Sciences": "Environmental Sciences",
    "Event Management": "Event Management",
    "Facebook Marketing": "Facebook Marketing",
    "Fashion Design": "Fashion Design",
    "Film Making": "Film Making",
    "Finance": "Finance",
    "Front End Development": "Front End Development",
    "Full Stack Development": "Full Stack Development",
    "Fundraising": "Fundraising",
    "Game Development": "Game Development",
    "General Management": "General Management",
    "Government": "Government",
    "Graphic Design": "Graphic Design",
    "Hospitality": "Hospitality",
    "Hotel Management": "Hotel Management",
    "Human Resources (HR)": "hr",
    "Humanities": "Humanities",
    "Image Processing": "Image Processing",
    "Industrial and Production Engineering": "Industrial and Production Engineering",
    "Industrial Design": "Industrial Design",
    "Information Technology": "Information Technology",
    "Interior Design": "Interior Design",
    "Internet of Things (IoT)": "Internet of Things (IoT)",
    "iOS App Development": "ios",
    "Java Development": "java",
    "Javascript Development": "Javascript Development",
    "Journalism": "Journalism",
    "Law": "Law",
    "Legal Research": "Legal Research",
    "Machine Learning": "Machine Learning",
    "Magento Development": "Magento Development",
    "Market/Business Research": "market%2Fbusiness%20research",
    "Marketing": "Marketing",
    "Material Science": "Material Science",
    "Mathematics": "Mathematics",
    "Mathematics and Computing": "Mathematics and Computing",
    "MBA": "MBA",
    "Mechanical Engineering": "mechanical",
    "Mechatronics": "Mechatronics",
    "Media": "Media",
    "Medicine": "Medicine",
    "Merchandise Design": "Merchandise Design",
    "Metallurgical Engineering": "metallurgy",
    "Mobile App Development": "Mobile App Development",
    "Motion Graphics": "Motion Graphics",
    "Naval Architecture and Ocean Engineeering": "naval and ocean",
    "Network Engineering": "Network Engineering",
    "NGO": "NGO",
    "Node.js Development": "Node.js Development",
    "Operations": "Operations",
    "Pharmaceutical": "Pharmaceutical",
    "Photography": "Photography",
    "PHP Development": "PHP Development",
    "Physics": "Physics",
    "Political/Economics/Policy Research": "political%2Feconomics%2Fpolicy research",
    "Public Relations (PR)": "pr",
    "Product Management": "product",
    "Programming": "Programming",
    "Psychology": "Psychology",
    "Python/Django Development": "python%2Fdjango",
    "Recruitment": "Recruitment",
    "Robotics": "Robotics",
    "Ruby on Rails": "Ruby on Rails",
    "Sales": "Sales",
    "Science": "Science",
    "Search Engine Optimization (SEO)": "Search Engine Optimization (SEO)",
    "Social Media Marketing": "Social Media Marketing",
    "Social Work": "Social Work",
    "Software Development": "Software Development",
    "Software Testing": "Software Testing",
    "Statistics": "Statistics",
    "Strategy": "Strategy",
    "Supply Chain Management (SCM)": "Supply Chain Management (SCM)",
    "Teaching": "Teaching",
    "Telecalling": "Telecalling",
    "Travel and Tourism": "Travel and Tourism",
    "UI/UX Design": "ui%2Fux",
    "Video Making/Editing": "video%20making%2Fediting",
    "Videography": "Videography",
    "Volunteering": "Volunteering",
    "Web Development": "Web Development",
    "Wordpress Development": "Wordpress Development"
}
